<?php

return [
    'domains' => [
        'hris' => env('HRIS_DOMAIN', 'hrismitogroup.web.id'),
        'mpr' => env('MPR_DOMAIN', 'mpr.hrismitogroup.web.id'),
        'recruitment' => env('RECRUITMENT_DOMAIN', 'recruitment.hrismitogroup.web.id'),
        'outsource' => env('OUTSOURCE_DOMAIN', 'outsource.hrismitogroup.web.id'),
        'assets' => env('ASSETS_DOMAIN', 'assets.hrismitogroup.web.id'),
        'certificates' => env('CERTIFICATES_DOMAIN', 'certificates.hrismitogroup.web.id'),
    ],
    'portal_access' => [
        'hris' => [
            'access' => 'private',
            'auth_source' => 'users',
        ],
        'mpr' => [
            'access' => 'private',
            'auth_source' => 'mpr_requestor',
        ],
        'outsource' => [
            'access' => 'public',
            'auth_source' => 'none',
        ],
        'recruitment' => [
            'access' => 'public',
            'auth_source' => 'none',
        ],
        'assets' => [
            'access' => 'private',
            'auth_source' => 'users',
        ],
        'certificates' => [
            'access' => 'private',
            'auth_source' => 'users',
        ],
    ],
    'mpr' => [
        'approval_divisions' => [
            'Aditya Adipradhana',
            'Destyani Wijaya',
            'Hisar Hesti',
            'Trian Nugroho',
        ],
        // Profil perusahaan untuk header/alamat PDF — di-resolve dari kode entity.
        'companies' => [
            'MSI' => [
                'name'    => 'PT MAHAKARYA SUKSES INDONESIA',
                'address' => 'Jl. Gajah Tunggal, Kp. Gembor, RT.004/RW.001, Kel. Pasir Jaya, Kec. Jatiuwung, Kota Tangerang, Banten 15135',
                'city'    => 'Tangerang',
                'brand'   => 'MITO',
                'code'    => 'MSI',
            ],
            'SPI' => [
                'name'    => 'PT STEIN PERKASA INTERNASIONAL',
                'address' => 'Rukan Mangga Dua Square Blok H No. 18-21, Jl. Gunung Sahari Raya Nomor 1, Kel. Ancol, Kec. Pademangan, Kota Jakarta Utara, DKI Jakarta - 14430',
                'city'    => 'Jakarta',
                'brand'   => 'STEIN',
                'code'    => 'SPI',
            ],
            'PII' => [
                'name'    => 'PT PERKASA INJEKSI INDONESIA',
                'address' => 'Jl. Gajah Tunggal, Kp. Gembor, RT.004/RW.001, Kel. Pasir Jaya, Kec. Jatiuwung, Kota Tangerang, Banten 15135',
                'city'    => 'Tangerang',
                'brand'   => 'PERKASA INJEKSI',
                'code'    => 'PII',
            ],
            'MEP' => [
                'name'    => 'PT MITRA ELEKTRO PERKASA',
                'address' => 'Rukan Mangga Dua Square Blok H No. 18-21, Jln. Gunung Sahari Raya Nomor 1, Kel. Ancol/Kec. Pademangan, Kota Jakarta Utara, DKI Jakarta',
                'city'    => 'Jakarta',
                'brand'   => 'MITRA ELEKTRO',
                'code'    => 'MEP',
            ],
        ],
    ],
    'mpr_department_divisions' => [
        'Human Resources' => [
            'HR Operations',
            'Recruitment & Talent Acquisition',
            'Learning & Development',
            'Compensation & Benefit',
            'People Development',
        ],
        'Finance' => [
            'Financial Planning & Analysis (FP&A)',
            'Treasury',
            'Finance Accounting',
            'Tax',
        ],
        'Accounting' => ['General Accounting', 'Accounts Payable', 'Accounts Receivable', 'Cost Accounting'],
        'Marketing' => ['Brand & Marketing', 'Digital Marketing', 'Marketing Communication', 'Trade Marketing'],
        'Digital Marketing' => ['Social Media', 'Performance Marketing', 'Content & Creative', 'E-Commerce'],
        'Sales' => ['Sales Operations', 'General Trade', 'Modern Trade', 'Key Account', 'Regional Sales', 'Sales Support'],
        'IT' => ['IT Infrastructure', 'IT Support', 'Software Development', 'IT Security', 'Data & Analytics'],
        'Engineering' => ['Mechanical Engineering', 'Electrical Engineering', 'Civil Engineering', 'Project Engineering', 'Maintenance Engineering'],
        'Operations' => ['Production', 'Production Planning', 'Operational Excellence', 'Warehouse Operations', 'Logistics'],
        'Legal' => ['Legal Corporate', 'Legal Compliance', 'Contract Management', 'Litigation'],
        'GA' => ['General Affairs', 'Facility Management', 'Asset Management', 'Office Services', 'Security'],
        'Warehouse' => ['Warehouse Operations', 'Inventory Control', 'Receiving', 'Picking & Packing', 'Distribution'],
        'Purchasing' => ['Procurement', 'Strategic Sourcing', 'Purchasing Operations', 'Vendor Management'],
        'Quality Control' => ['Quality Assurance', 'Quality Control', 'Quality Management System', 'Quality Inspection'],
        'Customer Service' => ['Customer Service Operations', 'Customer Support', 'Customer Complaint', 'After Sales Service'],
        'Creative' => ['Graphic Design', 'Multimedia', 'Content Production', 'Creative Design', 'Photography & Videography'],
    ],
    'mpr_form_options' => [
        // Single radio — Hari Kerja
        'working_days' => [
            'senin_jumat' => 'Senin - Jumat',
            'senin_sabtu' => 'Senin - Sabtu',
            'shifting'    => 'Shifting',
        ],
        // Single radio — Jam Kerja
        'working_hours' => [
            '08_00_17_00' => '08:00 - 17:00',
            '08_30_17_30' => '08:30 - 17:30',
        ],
        // Single radio — Benefits
        'benefits' => [
            'bpjs'                  => 'BPJS',
            'asuransi_kesehatan'    => 'Asuransi Kesehatan',
            'insentif_komisi'       => 'Insentif / Komisi',
            'tunjangan_pulsa'       => 'Tunjangan Pulsa',
            'tunjangan_transportasi' => 'Tunjangan Transportasi',
            'laptop_pc'             => 'Laptop / PC',
        ],
        // Single selection — Latar Belakang Pendidikan
        'education_background' => [
            'slta'  => 'SLTA',
            'd1_d3' => 'D1/D3',
            's1'    => 'S1',
            's2'    => 'S2',
        ],
        // Single selection — Pengalaman Kerja
        'work_experience' => [
            'fresh_graduate' => 'Fresh Graduate',
            '1_tahun'        => '1 Tahun',
            '2_3_tahun'      => '2-3 Tahun',
            'lebih_3_tahun'  => '> 3 Tahun',
        ],
        // Level jabatan (statis)
        'job_levels' => [
            'Associate',
            'Staff',
            'Senior Staff',
            'Supervisor',
            'Team Lead',
            'Manager',
            'General Manager',
            'Director',
        ],
        // Lokasi kerja penempatan (statis)
        'work_locations' => [
            'Head Office (HO)',
            'Depo Jakarta',
            'Depo Bandung',
            'Depo Surabaya',
            'Pabrik',
        ],
        // Status kepegawaian (statis)
        'employment_types' => [
            'Permanent (PKWTT)',
            'Contract (PKWT)',
            'Outsource',
            'Intern',
            'Freelance / Project',
        ],
        // Alasan permintaan MPR
        'reasons' => [
            'penambahan_karyawan_baru' => 'Penambahan Karyawan Baru',
            'penambahan_karyawan_baru_business_expansion' => 'Penambahan Karyawan Baru (Business Expansion)',
            'restrukturisasi' => 'Restrukturisasi',
            'penggantian_karyawan' => 'Penggantian Karyawan Resign / Mutasi / Demosi',
            'beban_kerja_musiman' => 'Beban Kerja Musiman / Peak Season',
            'proyek_khusus' => 'Proyek Khusus',
        ],
        'replacement_reasons' => [
            'Penambahan Karyawan Baru',
            'Penambahan Karyawan Baru (Business Expansion)',
            'Restrukturisasi',
        ],
        'target_entities' => [
            'MSI' => 'PT Mahakarya Sukses Indonesia (MSI)',
            'SPI' => 'PT Stein Perkasa Internasional (SPI)',
            'PII' => 'PT Perkasa Injeksi Indonesia (PII)',
            'MEP' => 'PT Mitra Elektro Perkasa (MEP)',
        ],
    ],
    'auth' => [
        'valid_roles' => [
            'Super Admin',
            'Admin',
            'User',
        ],
        // Manager role is NOT an internal HRIS role.
        // Manager accounts live in the mpr_requestor sheet, not Users.
        'valid_roles_internal' => [
            'Super Admin',
            'Admin',
            'User',
        ],
        'valid_roles_requestor' => [
            'Manpower',
        ],
        'role_aliases' => [
            'HR Manager' => 'Admin',
            'Privileged User' => 'User',
            'HR Recruitment' => 'User',
            'HR Staff' => 'User',
        ],
        'role_permissions' => [
            'Super Admin' => ['*'],
            'Admin' => ['manage_recruitment', 'manage_employees', 'manage_probation', 'view_employees', 'view_contracts', 'view_recruitment', 'update_candidates', 'create_offering', 'manage_hold_blacklist', 'view_mpr', 'create_mpr', 'update_mpr', 'export_mpr', 'assets.access', 'assets.view', 'assets.create', 'assets.update', 'assets.delete', 'assets.assign', 'assets.return', 'assets.generate_code', 'certificates.access', 'certificates.view', 'certificates.create', 'certificates.update', 'certificates.delete', 'certificates.generate_code', 'view_asset', 'edit_asset', 'view_certification', 'manage_certification'],
            'User' => ['view_recruitment', 'update_candidates', 'create_offering', 'manage_hold_blacklist', 'view_mpr', 'export_mpr', 'view_asset', 'view_certification'],
            'Manpower' => ['view_mpr', 'create_mpr', 'export_mpr'],
        ],
        'dedicated_portal_roles' => [
            'assets' => ['Super Admin', 'Admin'],
            'certificates' => ['Super Admin', 'Admin'],
        ],
    ],
    'schemas' => [
        'Employee' => [
            'Employee ID',
            'Full Name',
            'Branch Name',
            'Division',
            'Department',
            'Job Position (Location)',
            'Job Position',
            'Area Kerja',
            'Lokasi Kerja',
            'Job Level',
            'Grade',
            'Join Date',
            'Status Employee',
            'Direct Superior',
            'Indirect Superior',
            'Personal Email',
            'Working Email',
            'End Date (Contract)',
            'Birth Place',
            'Birth Date',
            'Citizen ID Address',
            'Residential Address',
            'NIK - NPWP 16 digit',
            'NPWP',
            'PTKP Status',
            'Bank Name',
            'Bank Account',
            'Bank Account Holder',
            'BPJS Ketenagakerjaan',
            'BPJS Kesehatan',
            'Mobile Phone',
            'Religion',
            'Gender',
            'Marital Status',
            'Blood Type',
            'Cost Center',
            'Job Position (Former)',
            'Type of Rotation',
            'Tanggal Mutasi/Demosi/Promosi',
            'Nomor SK',
            'Resign Date',
            'HR Notes',
            'Offboarding Type',
            'Offboarding Reason',
            'Offboarding Approved By',
            'Offboarding Documents Folder',
            'Offboarding Document Links',
            'Outsource Vendor',
            'Created By',
            'Created At',
            'Updated At',
            'Outsource Contract Seq',
        ],
        'data_kandidat' => [
            'Recruitment ID',
            'Created Date',
            'Full Name',
            'NIK',
            'Birth Date',
            'Age',
            'Gender',
            'Blood Type',
            'Marital Status',
            'Email',
            'Phone',
            'Address',
            'City',
            'Position Applied',
            'Education',
            'Work Experience',
            'Last Company',
            'Current Employment Status',
            'Available to Join',
            'Expected Salary',
            'Recruitment Source',
            'Status',
            'HR Notes',
            'Created By',
            'Updated At',
        ],
        'Audit_Log' => [
            'Audit ID',
            'Entity Type',
            'Entity ID',
            'Action',
            'Field',
            'Old Value',
            'New Value',
            'User',
            'Source',
            'Timestamp'
        ],
        'Users' => [
            'Email',
            'Username',
            'Full Name',
            'Role',
            'Status',
            'Password Hash',
            'Last Login',
            'Created At',
            'Updated At',
            'Created By',
        ],
        'Permissions' => [
            'Permission Key',
            'Name',
            'Description',
            'Group',
            'Status',
            'Created At',
            'Updated At',
        ],
        'User_Permissions' => [
            'User Email',
            'Permission Key',
            'Granted',
            'Granted By',
            'Created At',
            'Updated At',
        ],
        'kandidat_probation' => [
            // ── Identitas (col 1–3)
            'Probation ID',
            'Employee ID',
            'Recruitment ID',
            // ── Kontrak snapshot (col 4–7)
            'Contract Duration',
            'Contract Start',
            'Contract End',
            'Join Date',
            // ── Evaluation status (col 8)
            'Status',
            // ── Evaluasi header (col 9–10)
            'Eval ID',
            'Eval Date',
            // ── Decision
            'Decision',
            // ── Perpanjangan
            'Extension Duration',
            'New Contract Start',
            'New Contract End',
            // ── Catatan & SK
            'Evaluator Notes',
            'Evaluator',
            'SK Status',
            // ── Audit
            'Created At',
            'Updated At',
            // ── Performance Review 2026 — Competency totals
            // Dihitung server-side dari 13 behavioral indicator ✓/X.
            'Integrity Total',
            'CI Total',
            'EE Total',
            'Teamwork Total',
            'Overall Total',
            'Category',
            // ── Performance Review 2026 — Individual indicators
            // Disimpan sebagai "1" (✓ terpenuhi) atau "0" (X tidak terpenuhi).
            // Maximum score: 4+4+2+3 = 13. Kategori: 11-13 Sangat Baik, 8-10 Baik, 6-7 Cukup, 3-5 Kurang.
            'ind_integrity_1',
            'ind_integrity_2',
            'ind_integrity_3',
            'ind_integrity_4',
            'ind_ci_1',
            'ind_ci_2',
            'ind_ci_3',
            'ind_ci_4',
            'ind_ee_1',
            'ind_ee_2',
            'ind_tw_1',
            'ind_tw_2',
            'ind_tw_3',
            // Approval sign-off (Performance Review Section F)
            'Reviewer Name',
            'Approval Dept',
            'Approval Dept Name',
            'Approval Dept Date',
            'Approval HRBP',
            'Approval HRBP Name',
            'Approval HRBP Date',
        ],
        'kandidat_hold' => [
            'Recruitment ID',
            'Created Date',
            'Full Name',
            'NIK',
            'Birth Date',
            'Age',
            'Gender',
            'Blood Type',
            'Marital Status',
            'Email',
            'Phone',
            'Address',
            'City',
            'Position Applied',
            'Education',
            'Work Experience',
            'Last Company',
            'Current Employment Status',
            'Available to Join',
            'Expected Salary',
            'Recruitment Source',
            'Status',
            'HR Notes',
            'Created By',
            'Updated At',
            'Hold Reason',
            'Hold Follow Up Date',
            'Blacklist Reason',
            'Blacklist Date',
            'Blacklist Updated By',
            'Processed Date',
            'Processed By',
        ],
        'kandidat_accepted' => [
            'Recruitment ID',
            'Created Date',
            'Full Name',
            'NIK',
            'Birth Date',
            'Age',
            'Gender',
            'Blood Type',
            'Marital Status',
            'Email',
            'Phone',
            'Address',
            'City',
            'Position Applied',
            'Education',
            'Work Experience',
            'Last Company',
            'Current Employment Status',
            'Available to Join',
            'Expected Salary',
            'Recruitment Source',
            'Status',
            'HR Notes',
            'Created By',
            'Updated At',
            'Hold Reason',
            'Hold Follow Up Date',
            'Blacklist Reason',
            'Blacklist Date',
            'Blacklist Updated By',
            'Employee ID',
            'Processed Date',
            'Processed By',
            'Offering Created',
            'Offering Updated',
            'Offering Created By',
            'Offering Updated By',
            'Offering Company Entity',
            'Offering Position',
            'Offering Salary',
            'Offering Join Date',
            'Offering Notes',
            'Offering Response',
            'Offering Response Notes',
            'Offering Response Date',
            'Offering Response By',
            'Onboarding Status',
            'Onboarding Date',
            'Onboarding By',
            'Offering Division',
            'Offering Job Level',
            'Offering Lokasi Kerja',
            'Offering Salary Basic',
            'Offering Allow Pulsa',
            'Offering Allow Transport',
            'Offering Employment Status',
            'Offering Contract Duration',
            'Offering Working Hours',
        ],
        'kandidat_blacklist' => [
            'Recruitment ID',
            'Created Date',
            'Full Name',
            'NIK',
            'Birth Date',
            'Age',
            'Gender',
            'Blood Type',
            'Marital Status',
            'Email',
            'Phone',
            'Address',
            'City',
            'Position Applied',
            'Education',
            'Work Experience',
            'Last Company',
            'Current Employment Status',
            'Available to Join',
            'Expected Salary',
            'Recruitment Source',
            'Status',
            'HR Notes',
            'Created By',
            'Updated At',
            'Hold Reason',
            'Hold Follow Up Date',
            'Blacklist Reason',
            'Blacklist Date',
            'Blacklist Updated By',
            'Processed Date',
            'Processed By',
        ],
        'MPR' => [
            'MPR Number',
            'Request Date',
            'Requestor Name',
            'Requestor Email',
            'Entitas yang Dituju',
            'Department',
            'Division',
            'Approval Division',
            'Position',
            'Job Level',
            'Work Location',
            'Employment Type',
            'Quantity',
            'Expected Join Date',
            'Reason',
            'Replacement For',
            'Job Description',
            'Requirements',
            // 'Notes',
            // -- Refactor Create MPR: field baru (append-only, backward compatible) --
            'Requestor Position',
            'Working Days',
            'Working Hours',
            'Shift Detail',
            'Benefits',
            'Education Background',
            'Work Experience',
            'Skills / Competencies',
            'Languages',
            'Industry Reference',
            'Special Notes',
            'Key Results / Targets',
            'Status',
            'Created By',
            'Created At',
            'Updated At',
        ],
        'mpr_requestor' => [
            'Requestor ID',
            'Email',
            'Username',
            'Full Name',
            'Job Position',
            'Role',
            'Status',
            'Password Hash',
            'Last Login',
            'Created At',
            'Updated At',
            'Created By',
        ],
    ],
];
