<?php

$positions = [
        ['Sales Director', 'Sales', 'Director'],
        ['Head of Sales', 'Sales', 'Head'],
        ['Sales Manager', 'Sales', 'Manager'],
        ['Area Sales Manager', 'Sales', 'Manager'],
        ['Sales Supervisor', 'Sales', 'Supervisor'],
        ['Sales Executive', 'Sales', 'Staff'],
        ['Sales Representative', 'Sales', 'Staff'],
        ['Sales Promotor', 'Sales', 'Staff'],
        ['Key Account Manager', 'Sales', 'Manager'],
        ['Key Account Executive', 'Sales', 'Staff'],
        ['Business Development Manager', 'Sales', 'Manager'],
        ['Business Development Executive', 'Sales', 'Staff'],
        ['Sales Coordinator', 'Sales', 'Staff'],
        ['Sales Administrator', 'Sales', 'Staff'],
        ['Sales Operations Specialist', 'Sales', 'Specialist'],
        ['Marketing Director', 'Marketing', 'Director'],
        ['Head of Marketing', 'Marketing', 'Head'],
        ['Product Marketing Manager', 'Marketing', 'Manager'],
        ['Product Marketing Executive', 'Marketing', 'Staff'],
        ['Product Specialist', 'Marketing', 'Specialist'],
        ['Trade Marketing Manager', 'Marketing', 'Manager'],
        ['Trade Marketing Executive', 'Marketing', 'Staff'],
        ['Merchandising Specialist', 'Marketing', 'Specialist'],
        ['Brand Marketing Manager', 'Marketing', 'Manager'],
        ['Brand Marketing Executive', 'Marketing', 'Staff'],
        ['Marketing Communication Specialist', 'Marketing', 'Specialist'],
        ['Creative & Content Manager', 'Marketing', 'Manager'],
        ['Graphic Designer', 'Marketing', 'Staff'],
        ['Video Editor', 'Marketing', 'Staff'],
        ['Content Creator', 'Marketing', 'Staff'],
        ['Social Media Specialist', 'Marketing', 'Specialist'],
        ['Head of Product Development', 'Product', 'Head'],
        ['Product Development Manager', 'Product', 'Manager'],
        ['Product Development Specialist', 'Product', 'Specialist'],
        ['Product Engineer', 'Product', 'Specialist'],
        ['Product Testing Engineer', 'Product', 'Specialist'],
        ['Product Sourcing Manager', 'Product', 'Manager'],
        ['Product Sourcing Specialist', 'Product', 'Specialist'],
        ['Supply Chain Manager', 'Supply Chain', 'Manager'],
        ['Demand Planner', 'Supply Chain', 'Specialist'],
        ['Supply Planner', 'Supply Chain', 'Specialist'],
        ['Inventory Planner', 'Supply Chain', 'Specialist'],
        ['Supply Chain Analyst', 'Supply Chain', 'Specialist'],
        ['Procurement Manager', 'Procurement', 'Manager'],
        ['Procurement Specialist', 'Procurement', 'Specialist'],
        ['Purchasing Officer', 'Procurement', 'Staff'],
        ['Vendor Management Specialist', 'Procurement', 'Specialist'],
        ['Logistics Manager', 'Logistics', 'Manager'],
        ['Logistics Supervisor', 'Logistics', 'Supervisor'],
        ['Logistics Coordinator', 'Logistics', 'Staff'],
        ['Warehouse Manager', 'Logistics', 'Manager'],
        ['Warehouse Supervisor', 'Logistics', 'Supervisor'],
        ['Warehouse Staff', 'Logistics', 'Staff'],
        ['Plant Manager', 'Manufacturing', 'Manager'],
        ['Production Manager', 'Manufacturing', 'Manager'],
        ['Production Supervisor', 'Manufacturing', 'Supervisor'],
        ['Production Engineer', 'Manufacturing', 'Specialist'],
        ['Production Planner', 'Manufacturing', 'Specialist'],
        ['Production Leader', 'Manufacturing', 'Leader'],
        ['Production Operator', 'Manufacturing', 'Operator'],
        ['Engineering Manager', 'Engineering', 'Manager'],
        ['Process Engineer', 'Engineering', 'Specialist'],
        ['Industrial Engineer', 'Engineering', 'Specialist'],
        ['Maintenance Supervisor', 'Engineering', 'Supervisor'],
        ['Maintenance Technician', 'Engineering', 'Technician'],
        ['Quality Manager', 'Quality', 'Manager'],
        ['Quality Assurance Specialist', 'Quality', 'Specialist'],
        ['Quality Control Specialist', 'Quality', 'Specialist'],
        ['QA Engineer', 'Quality', 'Specialist'],
        ['QC Engineer', 'Quality', 'Specialist'],
        ['Quality Inspector', 'Quality', 'Staff'],
        ['Finance Manager', 'Finance', 'Manager'],
        ['Accounting Manager', 'Finance', 'Manager'],
        ['Finance Specialist', 'Finance', 'Specialist'],
        ['Accounting Specialist', 'Finance', 'Specialist'],
        ['Account Payable Specialist', 'Finance', 'Specialist'],
        ['Account Receivable Specialist', 'Finance', 'Specialist'],
        ['Treasury Specialist', 'Finance', 'Specialist'],
        ['Tax Specialist', 'Finance', 'Specialist'],
        ['Cost Accounting Specialist', 'Finance', 'Specialist'],
        ['Financial Analyst', 'Finance', 'Specialist'],
        ['Internal Audit Manager', 'Audit & Risk', 'Manager'],
        ['Internal Auditor', 'Audit & Risk', 'Specialist'],
        ['Risk Management Specialist', 'Audit & Risk', 'Specialist'],
        ['HR Manager', 'HR', 'Manager'],
        ['HR Business Partner', 'HR', 'Specialist'],
        ['HR Generalist', 'HR', 'Specialist'],
        ['Talent Acquisition Specialist', 'HR', 'Specialist'],
        ['Learning & Development Specialist', 'HR', 'Specialist'],
        ['Organization Development Specialist', 'HR', 'Specialist'],
        ['Compensation & Benefit Specialist', 'HR', 'Specialist'],
        ['Payroll Specialist', 'HR', 'Specialist'],
        ['Industrial Relations Specialist', 'HR', 'Specialist'],
        ['HR Administrator', 'HR', 'Staff'],
        ['IT Manager', 'IT', 'Manager'],
        ['IT Support Specialist', 'IT', 'Specialist'],
        ['System Administrator', 'IT', 'Specialist'],
        ['Network Engineer', 'IT', 'Specialist'],
        ['ERP Specialist', 'IT', 'Specialist'],
        ['Data Analyst', 'IT', 'Specialist'],
        ['Business Intelligence Analyst', 'IT', 'Specialist'],
        ['Legal Manager', 'Legal', 'Manager'],
        ['Legal Specialist', 'Legal', 'Specialist'],
        ['Compliance Specialist', 'Legal', 'Specialist'],
        ['Corporate Secretary', 'Corporate', 'Specialist'],
        ['Corporate Affairs Specialist', 'Corporate', 'Specialist'],
        ['Customer Service Manager', 'Customer Experience', 'Manager'],
        ['Customer Service Supervisor', 'Customer Experience', 'Supervisor'],
        ['Customer Service Officer', 'Customer Experience', 'Staff'],
        ['Customer Experience Specialist', 'Customer Experience', 'Specialist'],
        ['After Sales Manager', 'After Sales', 'Manager'],
        ['After Sales Specialist', 'After Sales', 'Specialist'],
        ['Warranty Specialist', 'After Sales', 'Specialist'],
        ['Technical Support Specialist', 'After Sales', 'Specialist'],
        ['Service Center Supervisor', 'After Sales', 'Supervisor'],
        ['General Affairs Manager', 'GA & Facility', 'Manager'],
        ['General Affairs Specialist', 'GA & Facility', 'Specialist'],
        ['Facility Management Specialist', 'GA & Facility', 'Specialist'],
        ['Receptionist', 'GA & Facility', 'Staff'],
        ['Driver', 'GA & Facility', 'Staff'],
    ];

return ['positions' => $positions];

/*

    'get_level' => function($position) {
        $map = [
            'Sales Director' => 'Director',
            'Head of Sales' => 'Head',
            'Sales Manager' => 'Manager',
            'Area Sales Manager' => 'Manager',
            'Sales Supervisor' => 'Supervisor',
            'Sales Executive' => 'Staff',
            'Sales Representative' => 'Staff',
            'Sales Promotor' => 'Staff',
            'Key Account Manager' => 'Manager',
            'Key Account Executive' => 'Staff',
            'Business Development Manager' => 'Manager',
            'Business Development Executive' => 'Staff',
            'Sales Coordinator' => 'Staff',
            'Sales Administrator' => 'Staff',
            'Sales Operations Specialist' => 'Specialist',
            'Marketing Director' => 'Director',
            'Head of Marketing' => 'Head',
            'Product Marketing Manager' => 'Manager',
            'Product Marketing Executive' => 'Staff',
            'Product Specialist' => 'Specialist',
            'Trade Marketing Manager' => 'Manager',
            'Trade Marketing Executive' => 'Staff',
            'Merchandising Specialist' => 'Specialist',
            'Brand Marketing Manager' => 'Manager',
            'Brand Marketing Executive' => 'Staff',
            'Marketing Communication Specialist' => 'Specialist',
            'Creative & Content Manager' => 'Manager',
            'Graphic Designer' => 'Staff',
            'Video Editor' => 'Staff',
            'Content Creator' => 'Staff',
            'Social Media Specialist' => 'Specialist',
            'Head of Product Development' => 'Head',
            'Product Development Manager' => 'Manager',
            'Product Development Specialist' => 'Specialist',
            'Product Engineer' => 'Specialist',
            'Product Testing Engineer' => 'Specialist',
            'Product Sourcing Manager' => 'Manager',
            'Product Sourcing Specialist' => 'Specialist',
            'Supply Chain Manager' => 'Manager',
            'Demand Planner' => 'Specialist',
            'Supply Planner' => 'Specialist',
            'Inventory Planner' => 'Specialist',
            'Supply Chain Analyst' => 'Specialist',
            'Procurement Manager' => 'Manager',
            'Procurement Specialist' => 'Specialist',
            'Purchasing Officer' => 'Staff',
            'Vendor Management Specialist' => 'Specialist',
            'Logistics Manager' => 'Manager',
            'Logistics Supervisor' => 'Supervisor',
            'Logistics Coordinator' => 'Staff',
            'Warehouse Manager' => 'Manager',
            'Warehouse Supervisor' => 'Supervisor',
            'Warehouse Staff' => 'Staff',
            'Plant Manager' => 'Manager',
            'Production Manager' => 'Manager',
            'Production Supervisor' => 'Supervisor',
            'Production Engineer' => 'Specialist',
            'Production Planner' => 'Specialist',
            'Production Leader' => 'Leader',
            'Production Operator' => 'Operator',
            'Engineering Manager' => 'Manager',
            'Process Engineer' => 'Specialist',
            'Industrial Engineer' => 'Specialist',
            'Maintenance Supervisor' => 'Supervisor',
            'Maintenance Technician' => 'Technician',
            'Quality Manager' => 'Manager',
            'Quality Assurance Specialist' => 'Specialist',
            'Quality Control Specialist' => 'Specialist',
            'QA Engineer' => 'Specialist',
            'QC Engineer' => 'Specialist',
            'Quality Inspector' => 'Staff',
            'Finance Manager' => 'Manager',
            'Accounting Manager' => 'Manager',
            'Finance Specialist' => 'Specialist',
            'Accounting Specialist' => 'Specialist',
            'Account Payable Specialist' => 'Specialist',
            'Account Receivable Specialist' => 'Specialist',
            'Treasury Specialist' => 'Specialist',
            'Tax Specialist' => 'Specialist',
            'Cost Accounting Specialist' => 'Specialist',
            'Financial Analyst' => 'Specialist',
            'Internal Audit Manager' => 'Manager',
            'Internal Auditor' => 'Specialist',
            'Risk Management Specialist' => 'Specialist',
            'HR Manager' => 'Manager',
            'HR Business Partner' => 'Specialist',
            'HR Generalist' => 'Specialist',
            'Talent Acquisition Specialist' => 'Specialist',
            'Learning & Development Specialist' => 'Specialist',
            'Organization Development Specialist' => 'Specialist',
            'Compensation & Benefit Specialist' => 'Specialist',
            'Payroll Specialist' => 'Specialist',
            'Industrial Relations Specialist' => 'Specialist',
            'HR Administrator' => 'Staff',
            'IT Manager' => 'Manager',
            'IT Support Specialist' => 'Specialist',
            'System Administrator' => 'Specialist',
            'Network Engineer' => 'Specialist',
            'ERP Specialist' => 'Specialist',
            'Data Analyst' => 'Specialist',
            'Business Intelligence Analyst' => 'Specialist',
            'Legal Manager' => 'Manager',
            'Legal Specialist' => 'Specialist',
            'Compliance Specialist' => 'Specialist',
            'Corporate Secretary' => 'Specialist',
            'Corporate Affairs Specialist' => 'Specialist',
            'Customer Service Manager' => 'Manager',
            'Customer Service Supervisor' => 'Supervisor',
            'Customer Service Officer' => 'Staff',
            'Customer Experience Specialist' => 'Specialist',
            'After Sales Manager' => 'Manager',
            'After Sales Specialist' => 'Specialist',
            'Warranty Specialist' => 'Specialist',
            'Technical Support Specialist' => 'Specialist',
            'Service Center Supervisor' => 'Supervisor',
            'General Affairs Manager' => 'Manager',
            'General Affairs Specialist' => 'Specialist',
            'Facility Management Specialist' => 'Specialist',
            'Receptionist' => 'Staff',
            'Driver' => 'Staff',
        ];
        return $map[$position] ?? null;
    },

    'get_family' => function($position) {
        $map = [
            'Sales Director' => 'Sales',
            'Head of Sales' => 'Sales',
            'Sales Manager' => 'Sales',
            'Area Sales Manager' => 'Sales',
            'Sales Supervisor' => 'Sales',
            'Sales Executive' => 'Sales',
            'Sales Representative' => 'Sales',
            'Sales Promotor' => 'Sales',
            'Key Account Manager' => 'Sales',
            'Key Account Executive' => 'Sales',
            'Business Development Manager' => 'Sales',
            'Business Development Executive' => 'Sales',
            'Sales Coordinator' => 'Sales',
            'Sales Administrator' => 'Sales',
            'Sales Operations Specialist' => 'Sales',
            'Marketing Director' => 'Marketing',
            'Head of Marketing' => 'Marketing',
            'Product Marketing Manager' => 'Marketing',
            'Product Marketing Executive' => 'Marketing',
            'Product Specialist' => 'Marketing',
            'Trade Marketing Manager' => 'Marketing',
            'Trade Marketing Executive' => 'Marketing',
            'Merchandising Specialist' => 'Marketing',
            'Brand Marketing Manager' => 'Marketing',
            'Brand Marketing Executive' => 'Marketing',
            'Marketing Communication Specialist' => 'Marketing',
            'Creative & Content Manager' => 'Marketing',
            'Graphic Designer' => 'Marketing',
            'Video Editor' => 'Marketing',
            'Content Creator' => 'Marketing',
            'Social Media Specialist' => 'Marketing',
            'Head of Product Development' => 'Product',
            'Product Development Manager' => 'Product',
            'Product Development Specialist' => 'Product',
            'Product Engineer' => 'Product',
            'Product Testing Engineer' => 'Product',
            'Product Sourcing Manager' => 'Product',
            'Product Sourcing Specialist' => 'Product',
            'Supply Chain Manager' => 'Supply Chain',
            'Demand Planner' => 'Supply Chain',
            'Supply Planner' => 'Supply Chain',
            'Inventory Planner' => 'Supply Chain',
            'Supply Chain Analyst' => 'Supply Chain',
            'Procurement Manager' => 'Procurement',
            'Procurement Specialist' => 'Procurement',
            'Purchasing Officer' => 'Procurement',
            'Vendor Management Specialist' => 'Procurement',
            'Logistics Manager' => 'Logistics',
            'Logistics Supervisor' => 'Logistics',
            'Logistics Coordinator' => 'Logistics',
            'Warehouse Manager' => 'Logistics',
            'Warehouse Supervisor' => 'Logistics',
            'Warehouse Staff' => 'Logistics',
            'Plant Manager' => 'Manufacturing',
            'Production Manager' => 'Manufacturing',
            'Production Supervisor' => 'Manufacturing',
            'Production Engineer' => 'Manufacturing',
            'Production Planner' => 'Manufacturing',
            'Production Leader' => 'Manufacturing',
            'Production Operator' => 'Manufacturing',
            'Engineering Manager' => 'Engineering',
            'Process Engineer' => 'Engineering',
            'Industrial Engineer' => 'Engineering',
            'Maintenance Supervisor' => 'Engineering',
            'Maintenance Technician' => 'Engineering',
            'Quality Manager' => 'Quality',
            'Quality Assurance Specialist' => 'Quality',
            'Quality Control Specialist' => 'Quality',
            'QA Engineer' => 'Quality',
            'QC Engineer' => 'Quality',
            'Quality Inspector' => 'Quality',
            'Finance Manager' => 'Finance',
            'Accounting Manager' => 'Finance',
            'Finance Specialist' => 'Finance',
            'Accounting Specialist' => 'Finance',
            'Account Payable Specialist' => 'Finance',
            'Account Receivable Specialist' => 'Finance',
            'Treasury Specialist' => 'Finance',
            'Tax Specialist' => 'Finance',
            'Cost Accounting Specialist' => 'Finance',
            'Financial Analyst' => 'Finance',
            'Internal Audit Manager' => 'Audit & Risk',
            'Internal Auditor' => 'Audit & Risk',
            'Risk Management Specialist' => 'Audit & Risk',
            'HR Manager' => 'HR',
            'HR Business Partner' => 'HR',
            'HR Generalist' => 'HR',
            'Talent Acquisition Specialist' => 'HR',
            'Learning & Development Specialist' => 'HR',
            'Organization Development Specialist' => 'HR',
            'Compensation & Benefit Specialist' => 'HR',
            'Payroll Specialist' => 'HR',
            'Industrial Relations Specialist' => 'HR',
            'HR Administrator' => 'HR',
            'IT Manager' => 'IT',
            'IT Support Specialist' => 'IT',
            'System Administrator' => 'IT',
            'Network Engineer' => 'IT',
            'ERP Specialist' => 'IT',
            'Data Analyst' => 'IT',
            'Business Intelligence Analyst' => 'IT',
            'Legal Manager' => 'Legal',
            'Legal Specialist' => 'Legal',
            'Compliance Specialist' => 'Legal',
            'Corporate Secretary' => 'Corporate',
            'Corporate Affairs Specialist' => 'Corporate',
            'Customer Service Manager' => 'Customer Experience',
            'Customer Service Supervisor' => 'Customer Experience',
            'Customer Service Officer' => 'Customer Experience',
            'Customer Experience Specialist' => 'Customer Experience',
            'After Sales Manager' => 'After Sales',
            'After Sales Specialist' => 'After Sales',
            'Warranty Specialist' => 'After Sales',
            'Technical Support Specialist' => 'After Sales',
            'Service Center Supervisor' => 'After Sales',
            'General Affairs Manager' => 'GA & Facility',
            'General Affairs Specialist' => 'GA & Facility',
            'Facility Management Specialist' => 'GA & Facility',
            'Receptionist' => 'GA & Facility',
            'Driver' => 'GA & Facility',
        ];
        return $map[$position] ?? null;
    },
*/